package WEEK1;

public class PolicyException extends Exception
{
    private int ID;

    public PolicyException (int ID)
    {
        this.ID = ID;
    }

    public int getID ()
    {
        return ID;
    }

    public String toString ()
    {
        return "The Policy ID was not valid and a new ID " + ID + " is generated by admin and assigned for the Policy";
    }
}
